print("DIRECTORIO PERSONAL")

Nombre = input("Dame tu nombre: ")
Edad = input("Dame tu edad: ")
FN = input("Dame tu fecha de nacimiento: ")
Calle = input("Ingresa tu calle: ")
NumExt = input("Numero de la casa: ")
Colonia = input("Ingresa la colonia: ")
Ciudad = input("Ingresa la ciudad: ")
CP = input("Ingresa el codigo postal: ")
Tel = input("Ingresa un numero de telefono: ")

print("")
print("NOMBRE:", Nombre)
print("Edad:", Edad)
print("Fecha de Nacimiento:", FN)
print("Ciudad:", Ciudad)
print("Codigo Postal:", CP)
print("Calle:", Calle)
print("Colonia:", Colonia)
print("Numero Exterior:", NumExt)
print("Telefono:", Tel)
